name: Build and Deploy Go Binaries for Multiple OS

on: 
  push:
    branches:
      - main  # or any branch you want to trigger this action

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'  # specify the Go version you are using

    - name: Build project for ${{ matrix.os }} ${{ matrix.arch }}
      run: |
        mkdir -p bin/${{ matrix.os }}_${{ matrix.arch }}
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./bin/${{ matrix.os }}_${{ matrix.arch }}/myapp
      env:
        CGO_ENABLED: 0

    - name: Zip binaries
      run: zip -r binaries.zip ./bin

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: binaries.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: <target-repo-owner>/<target-repo-name>  # replace with the owner/repo
        token: ${{ secrets.PUSH_TOKEN }}
        path: target-repo

    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: binaries
        path: .

    - name: Unzip binaries
      run: unzip binaries.zip -d .

    - name: Copy binaries to target repository
      run: |
        cp -r ./bin/* ./target-repo/bin

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        cd target-repo
        git pull origin main  # Pull the latest changes from the remote repository
        git add .
        git commit -m "Update binaries for multiple OS"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
