---
name: deploy
on:
  workflow_dispatch: {}
  push:
    branches: [master]

jobs:
  deploy-function:
    name: Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
      REGION: ${{ secrets.REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: "google-github-actions/auth@v2"
        id: "auth"
        name: "Authenitication"
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: "Deploy Function"
        id: "deploy2"
        run: "gcloud functions deploy ${{ env.FUNCTION_NAME }} --gen2 --runtime=go122 --region=${{ env.REGION }} --source=. --trigger-http --allow-unauthenticated --entry-point=RenderSubtitles"

      - name: Get url
        id: getUrl
        run: echo "url=$(gcloud functions describe ${{ env.FUNCTION_NAME }} --gen2 --region europe-west2 --format json | jq .url -r)" >> $GITHUB_OUTPUT

